export const BASE_URL = process.env.REACT_APP_BACK_END_API;
export const CLOUDINARY_CLOUD_NAME = process.env.REACT_APP_CLOUDINARY_CLOUD_NAME;
export const CLOUDINARY_UPLOAD_PRESET = process.env.REACT_APP_CLOUDINARY_UPLOAD_PRESET;
export const DONATIONS_LIMIT_PER_PAGE= 5;
export const PROJECTS_LIMIT_PER_PAGE = 6;